icon_mapping = {
    "airport": "1",
    "amusement park": "2",
    "anchor": "3",
    "ball park": "4",
    "bank": "5",
    "bar": "6",
    "boat ramp": "7",
    "bowling": "8",
    "bridge": "9",
    "building": "10",
    "campground": "11",
    "car": "12",
    "car rental": "13",
    "car repair": "14",
    "cemetery": "15",
    "church": "16",
    "city (large)": "17",
    "city (medium)": "18",
    "city (small)": "19",
    "convenience store": "20",
    "crossing": "76",  # should be 21, but it seems like the website uses 76.
    "dam": "22",
    "danger area": "23",
    "dangerous area": "24",
    "department store": "25",
    "drinking water": "26",
    "fast food": "27",
    "fishing area": "28",
    "fitness center": "29",
    "forest": "30",
    "gas station": "31",
    "geocache": "32",
    "geocache found": "33",
    "glider area": "34",
    "golf course": "35",
    "hotel": "36",
    "hunting area": "37",
    "information": "38",
    "live theater": "39",
    "man overboard": "40",
    "medical facility": "41",
    "mine": "42",
    "movie theater": "43",
    "museum": "44",
    "oil field": "45",
    "parachute area": "46",
    "park": "47",
    "parking area": "48",
    "pharmacy": "49",
    "picnic area": "50",
    "pizza": "51",
    "post office": "52",
    "rv park": "53",
    "residence": "54",
    "restaurant": "55",
    "restroom": "56",
    "scales": "57",
    "scenic area": "58",
    "school": "59",
    "seaplane base": "60",
    "shipwreck": "61",
    "shopping center": "62",
    "short tower": "63",
    "shower": "64",
    "skiing area": "65",
    "stadium": "66",
    "summit": "67",
    "swimming area": "68",
    "tall tower": "69",
    "telephone": "70",
    "toll booth": "71",
    "trail head": "72",
    "truck stop": "73",
    "tunnel": "74",
    "ultralight area": "75",
    "waypoint": "76",
    "zoo": "77",
    "repülőtér": "1",
    "szórakozó park": "2",
    "horgony": "3",
    "szabadidő park": "4",
    "bank": "5",
    "bár": "6",
    "sója": "7",
    "bowling": "8",
    "híd": "9",
    "épület": "10",
    "kemping": "11",
    "szerviz": "12",
    "autókölcsönző": "13",
    "autószerviz": "14",
    "temető": "15",
    "templom": "16",
    "város (nagy)": "17",
    "város (közepes)": "18",
    "város (kicsi)": "19",
    "vegyes bolt": "20",
    # should be 21, but it seems like the website uses 76.
    "kereszteződés": "76",
    "gát": "22",
    "veszélyes terület": "23",
    "veszélyes terület": "24",
    "bevásárló központ": "25",
    "ivóvíz": "26",
    "gyorsétterem": "27",
    "horgász hely": "28",
    "fitness center": "29",
    "erdő": "30",
    "benzinkút": "31",
    "geocache": "32",
    "megtalált geocache": "33",
    "vitorlázó reptér": "34",
    "golf pálya": "35",
    "hotel": "36",
    "vadász terület": "37",
    "információ": "38",
    "színház": "39",
    "ember a vízben": "40",
    "orvosi rendelő": "41",
    "bánya": "42",
    "mozi": "43",
    "múzeum": "44",
    "olajmező": "45",
    "ejtőernyős terület": "46",
    "park": "47",
    "parkoló": "48",
    "gyógyszertár": "49",
    "pihenő terület": "50",
    "pizzéria": "51",
    "posta": "52",
    "rv park": "53",
    "otthon": "54",
    "étterem": "55",
    "wc": "56",
    "léptékek": "57",
    "látványos terület": "58",
    "iskola": "59",
    "hidroplán állomás": "60",
    "hajóroncs": "61",
    "bevásárló központ": "62",
    "alacsony torony": "63",
    "fürdő": "64",
    "síközpont": "65",
    "stadion": "66",
    "hegycsúcs": "67",
    "uszoda": "68",
    "magas torony": "69",
    "telefon": "70",
    "útdíj fizető hely": "71",
    "ösvény kezdete": "72",
    "kamion parkoló": "73",
    "csatorna/alagút": "74",
    "ultralight area": "75",
    "útpont": "76",
    "állatkert": "77"
}
